# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hashtag & Captions
email:
description: >- # this means to ignore newlines until "baseurl:"
  Make your social posts more engaging, likable, and appealing. Use the best hashtags and captions we drafted to suit your style.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
paginate: 7 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Hashtag & Captions"
  avatar : "/assets/images/bio.jpeg"
  bio    : "Make your social posts more engaging, likable, and appealing. 
  
          Use the best hashtags and captions we drafted just for your style."
  links:
    - label: "Top 50 Instagram"
      icon: "fa-solid fa-hashtag"
      url: "/post/top-50-instagram/"
    - label: "City Life"
      icon: "fa-solid fa-hashtag"
      url: "/tags/#city"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

comments:
  provider: "facebook"
  facebook:
    appid: 666515885079035
    num_posts: # 5
    colorscheme: # "light" (default), "dark"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      toc_ads: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-250090164-1"
    anonymize_ip         : true
